on: [push]
jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ammaraskar/gcc-problem-matcher@master
      - name: Compile
        run: |
          echo "::group::gcc"
          gcc -o hello_word hello_world.c
          echo "::endgroup::"
      - name: Test
        run: |
          ./hello_word > output.txt
          diff output.txt excepted.txt
