on: [push]
jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: thierry-martinez/custom-action-example@master
        with:
          source: hello_world.c
          target: hello_world
      - name: Test
        run: |
          ./hello_word > output.txt
          diff output.txt excepted.txt
